apiVersion: iis.cpd.ibm.com/v1alpha1
kind: IIS
metadata:
  name: iis-cr
spec:
  version: "4.0.0"
  StorageVendor: portworx
  license:
    accept: true
    license: Enterprise
  wkc_db2u_set_kernel_params: True  
  docker_registry_prefix: cp.stg.icr.io/cp/cpd
  use_dynamic_provisioning: true
  namespace: REPLACE_NAMESPACE