---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kube-system-operatorgroup
  namespace: kube-system
spec:
  serviceAccount:
    metadata:
      creationTimestamp: null
  targetNamespaces:
  - kube-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certified-operators
  namespace: openshift-marketplace
spec:
  displayName: Certified Operators
  icon:
    base64data: ''
    mediatype: ''
  image: portworx/oci-monitor:2.5.1
  publisher: Red Hat
  sourceType: grpc
---
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    generation: 1
    name: portworx-certified
    namespace: kube-system
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: portworx-certified
    source: certified-operators
    sourceNamespace: openshift-marketplace
    startingCSV:  portworx-operator.v1.2.0
